"use client";
import { useEffect, useRef, useState } from "react";
import { GraduationCap, Search, Building2, Hash, RefreshCw, ShieldCheck, ExternalLink, BookOpen, Newspaper, MapPin, Clock3, Info, BarChart3, School, Loader2 } from "lucide-react";
import { Input } from "@/components/ui/input";
import {SchoolInput,NationalSchools} from "@/components/national-schools";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableHeader, TableHead, TableBody, TableRow, TableCell } from "@/components/ui/table";
import { ChartContainer, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Empty, EmptyHeader, EmptyTitle, EmptyDescription } from "@/components/ui/empty";
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts";
type Row={year:number;college:string;name:string;code:string;mode:string;applicants:number|null;admitted:number|null;recommended?:number|null;score:number|null;average?:number|null;rank?:number|null;ratio:number|null;scoreSource?:string|null;source:string;note:string;province?:string;category?:string};
type Article={title:string;url:string;date:string;category:string;source:string};
type Result={school:string;rows:Row[];status:string;message:string;checkedAt:string|null;dataUpdatedAt:string;schoolInfo?:{region:string;city:string;level:string;department:string;id:string}|null;directory?:{name:string;url:string}[]};
const initial:Result={school:"南京邮电大学",status:"snapshot",message:"官方历史资料 · 正在检查更新",checkedAt:null,dataUpdatedAt:"2024-06-22",rows:[{year:2024,college:"计算机学院",name:"计算机技术",code:"085404",mode:"全日制",applicants:1809,admitted:225,recommended:3,score:339,ratio:1809/225,source:"https://yzb.njupt.edu.cn/2024/0622/c7813a269521/page.htm",note:"报名和录取人数均含推免，比例为同表报名人数 ÷ 录取人数。"}]};
const provinces=["北京","天津","河北","山西","内蒙古","辽宁","吉林","黑龙江","上海","江苏","浙江","安徽","福建","江西","山东","河南","湖北","湖南","广东","广西","海南","重庆","四川","贵州","云南","西藏","陕西","甘肃","青海","宁夏","新疆"];
const fmt=(v:number|null|undefined)=>v==null?"—":v.toLocaleString("zh-CN");
export default function Home(){
 const [type,setType]=useState("graduate"),[school,setSchool]=useState("南京邮电大学"),[code,setCode]=useState("085404"),[province,setProvince]=useState("安徽"),[category,setCategory]=useState("历史"),[result,setResult]=useState<Result>(initial),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const [program,setProgram]=useState("all"),[nationalOpen,setNationalOpen]=useState(false),[direction,setDirection]=useState("all");
 const [articles,setArticles]=useState<Article[]>([]),[newsStatus,setNewsStatus]=useState("正在获取官方公告"),[newsFilter,setNewsFilter]=useState("全部"),[detail,setDetail]=useState("overview"),[college,setCollege]=useState("all"),[mode,setMode]=useState("全日制"),[sourceOpen,setSourceOpen]=useState(false);
 const seq=useRef(0),newestQuery=useRef({school:"南京邮电大学",code:"085404",type:"graduate",province:"安徽",category:"历史"});
 async function query(options?:Partial<typeof newestQuery.current>){const values={school,code,type,province,category,...options};if(!values.school.trim()){setError("请输入学校名称。");return;}if(values.code&&!/^[0-9A-Za-z]{4,8}$/.test(values.code.trim())){setError("请输入 4–8 位专业代码，也可以留空查询该校已接入专业。");return;}const token=++seq.current;newestQuery.current=values;setLoading(true);setError("");try{const response=await fetch(`/api/query?${new URLSearchParams(values)}`,{cache:"no-store"});if(!response.ok)throw new Error("暂时无法获取数据，请稍后重试。");const data=await response.json() as Result;if(token===seq.current){setResult(data);setDirection(previous=>data.rows.some(r=>r.name===previous)?previous:"all");setProgram(previous=>previous!=="all"&&data.rows.some(r=>r.code===previous)?previous:values.code&&values.code.length===6?values.code:"all");const options=[...new Set(data.rows.map(r=>r.college))];setCollege(previous=>previous!=="all"&&options.includes(previous)?previous:options.includes("计算机学院")?"计算机学院":options.length>1?options[0]:"all");}return data;}catch(e){if(token===seq.current)setError(e instanceof Error?e.message:"查询失败");}finally{if(token===seq.current)setLoading(false);}}
 async function refreshNews(kind=type){try{const response=await fetch(`/api/news?type=${kind}`,{cache:"no-store"});if(!response.ok)throw new Error();const data=await response.json() as {articles:Article[];message:string};setArticles(data.articles);setNewsStatus(data.message);}catch{setNewsStatus("公告暂时无法更新，可通过官方入口查看。");}}
 function changeType(kind:string){setResult({school:kind==="graduate"?"南京邮电大学":"深圳大学",rows:[],status:"loading",message:"正在查询官方资料",checkedAt:null,dataUpdatedAt:""});setType(kind);setMode("全日制");setDetail("overview");setCollege("all");const next={type:kind,school:kind==="graduate"?"南京邮电大学":"深圳大学",code:kind==="graduate"?"085404":"030101K"};setSchool(next.school);setCode(next.code);query(next);refreshNews(kind);}
 useEffect(()=>{query();refreshNews();const timer=setInterval(()=>{if(document.visibilityState==="visible"){query(newestQuery.current);refreshNews(newestQuery.current.type);}},600000);return()=>clearInterval(timer);},[]);

 useEffect(()=>{
  const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;
  if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{Promise.resolve(context.registerTool({name:"query_admissions",title:"查询院校招生数据",description:"按学校与专业代码查询公开招生资料，并更新可见查询结果。高考需提供生源省份与科类。",inputSchema:{type:"object",properties:{school:{type:"string"},code:{type:"string"},type:{type:"string",enum:["graduate","undergraduate"]},province:{type:"string"},category:{type:"string"}},required:["school","type"],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async(input:unknown)=>{const q=input as Record<string,unknown>;if(!q||typeof q.school!=="string"||!["graduate","undergraduate"].includes(String(q.type))||q.code!==undefined&&(typeof q.code!=="string"||q.code!==""&&!/^[0-9A-Za-z]{4,8}$/.test(q.code)))throw new Error("无效查询条件");if(q.type==="undergraduate"&&(typeof q.province!=="string"||typeof q.category!=="string"))throw new Error("高考查询需提供省份与科类");const next={school:q.school,code:typeof q.code==="string"?q.code:"",type:String(q.type),province:typeof q.province==="string"?q.province:"安徽",category:typeof q.category==="string"?q.category:"历史"};setSchool(next.school);setCode(next.code);setType(next.type);setProvince(next.province);setCategory(next.category);const data=await query(next);if(!data)throw new Error("查询未完成");return {school:data.school,records:data.rows.length,status:data.status,message:data.message};}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[]);
 const beforeDirection=result.rows.filter(r=>(program==="all"||r.code===program)&&(college==="all"||r.college===college)&&(type==="undergraduate"||r.mode===mode));
 const directions=[...new Set(beforeDirection.map(r=>r.name))],filtered=beforeDirection.filter(r=>direction==="all"||r.name===direction);
 const groups=new Map<number,Row>();filtered.forEach(r=>{if(!groups.has(r.year))groups.set(r.year,r);});const history=[...groups.values()].sort((a,b)=>a.year-b.year),latest=history.at(-1),colleges=[...new Set(result.rows.map(r=>r.college))],ambiguous=(college==="all"&&colleges.length>1)||new Set(filtered.map(r=>r.code+"|"+r.name)).size>1,chart=ambiguous?[]:history.filter(r=>r.score!==null),ready=!!latest&&!ambiguous;
 return <div><header className="topbar"><a href="#query" className="brand"><span className="brand-mark"><GraduationCap size={25}/></span>升学指南<span className="brand-en">ADMISSIONS</span></a><nav aria-label="主导航"><a href="#query" className="nav-active">院校查询</a><a href="#history" onClick={()=>setDetail("history")}>历年数据</a><a href="#news">招生资讯</a></nav><button className="source-button" onClick={()=>setSourceOpen(true)}><ShieldCheck size={17}/><span>数据来源</span></button></header>
 <main className="workspace"><div className="page-heading"><div><div className="eyebrow">你的下一站，从这里开始</div><h1>把择校的每一步，走得更清楚<span>。</span></h1><p>院校、专业、历年数据与官方招生动态，一站查询。</p></div><div className="heading-label"><ShieldCheck size={19}/><span>公开资料可追溯<br/><small>官方来源 · 明确数据口径</small></span></div></div>
 <section id="query" className="query-card" aria-label="招生查询"><div className="query-top"><Tabs value={type} onValueChange={changeType}><TabsList className="exam-tabs"><TabsTrigger value="graduate"><GraduationCap/>考研择校</TabsTrigger><TabsTrigger value="undergraduate"><School/>高考择校</TabsTrigger></TabsList></Tabs><span className="query-caption">{type==="graduate"?"硕士研究生招生":"普通高校招生"}</span></div><form className={`search-form ${type==="undergraduate"?"undergraduate-form":""}`} onSubmit={e=>{e.preventDefault();query();}}><label className="search-field"><span><Building2 size={16}/>学校名称</span><SchoolInput value={school} onChange={setSchool} kind={type}/></label><label className="search-field"><span><Hash size={16}/>专业代码</span><Input aria-label="专业代码" value={code} onChange={e=>setCode(e.target.value)} placeholder="如 085404，可留空"/></label>{type==="undergraduate"&&<><div className="search-field"><label id="province-label"><MapPin size={16}/>生源省份</label><Select value={province} onValueChange={setProvince}><SelectTrigger aria-labelledby="province-label"><SelectValue/></SelectTrigger><SelectContent>{provinces.map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select></div><div className="search-field"><label id="category-label">科类</label><Select value={category} onValueChange={setCategory}><SelectTrigger aria-labelledby="category-label"><SelectValue/></SelectTrigger><SelectContent>{["历史","物理","综合改革","文科","理科"].map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select></div></>}<Button type="submit" className="search-button" disabled={loading}>{loading?<Loader2 className="spin"/>:<Search size={19}/>}查询数据</Button></form><div className="quick-search"><span>试试这些</span>{(type==="graduate"?[["南京邮电大学","085404"],["江苏大学","085404"],["南开大学","081200"]]:[["深圳大学","030101K"],["深圳大学","020101"],["深圳大学","120203K"]]).map(([s,c])=><button key={s+c} onClick={()=>{setSchool(s);setCode(c);query({school:s,code:c});}}>{s}<span>{c}</span></button>)}<button type="button" className="national-open" onClick={()=>setNationalOpen(true)}><Building2 size={14}/>全国高校库 · 2,952 所</button></div></section>
 {error&&<div className="error-banner" role="alert"><Info size={18}/>{error}</div>}<div className="content-grid"><div className="results-column" aria-busy={loading}>
 <section className="result-heading"><div className="school-avatar"><Building2 size={28}/></div><div className="school-title"><div className="school-name"><h2>{result.school}</h2><span className="tag">{type==="graduate"?"研究生招生":"高考招生"}</span></div><p>{latest?`${latest.code} ${latest.name}`:code||"招生数据"}<span> / </span>{latest?.college||"全国院校查询"}</p></div><button className="refresh-button" onClick={()=>query()} disabled={loading} aria-label="检查数据更新"><RefreshCw size={18} className={loading?"spin":""}/><span>检查更新</span></button></section>
 {result.schoolInfo&&<div className="school-profile"><MapPin size={13}/>{result.schoolInfo.region} · {result.schoolInfo.level}<span>{result.schoolInfo.department}</span><small>教育部名录已匹配</small></div>}<div className="data-status"><Clock3 size={14}/><span>{loading?"正在查询官方来源…":result.message}</span>{result.checkedAt&&<span className="checked-at">检查于 {new Date(result.checkedAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"})}</span>}</div>
 {!loading&&!result.rows.length&&<div className="uncovered-materials"><div><BookOpen size={22}/><strong>历史统计尚未接入，先查官方招生资料</strong></div><p>已公开的分数线、招生简章与专业目录，请通过以下官方入口核对。未公开的报名人数不会生成报录比。</p><div className="official-link-grid">{result.directory?.map(d=><a href={d.url} key={d.url} target="_blank" rel="noreferrer">{d.name}<ExternalLink size={14}/></a>)}</div></div>}{new Set(result.rows.map(r=>r.code)).size>1&&<div className="result-filters"><span>选择专业查看独立数据</span><Select value={program} onValueChange={setProgram}><SelectTrigger aria-label="选择专业"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部专业</SelectItem>{[...new Map(result.rows.map(r=>[r.code,r.name])).entries()].map(([c,n])=><SelectItem key={c} value={c}>{c} · {n}</SelectItem>)}</SelectContent></Select></div>}{colleges.length>1&&<div className="result-filters"><span>选择学院查看独立统计</span><Select value={college} onValueChange={setCollege}><SelectTrigger aria-label="选择学院"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部学院</SelectItem>{colleges.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div>}{type==="graduate"&&result.rows.some(r=>r.mode==="非全日制")&&<Tabs value={mode} onValueChange={setMode} className="mode-switch"><TabsList><TabsTrigger value="全日制">全日制</TabsTrigger><TabsTrigger value="非全日制">非全日制</TabsTrigger></TabsList></Tabs>}
 {directions.length>1&&new Set(beforeDirection.map(r=>r.code)).size===1&&<div className="result-filters"><span>选择专业方向</span><Select value={direction} onValueChange={setDirection}><SelectTrigger aria-label="选择专业方向"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部方向</SelectItem>{directions.map(d=><SelectItem key={d} value={d}>{d}</SelectItem>)}</SelectContent></Select></div>}<div className="metric-grid"><div className="metric metric-primary"><div className="metric-label">{type==="graduate"?"报录比":"录取最低分"}<BarChart3 size={17}/></div><div className="metric-value">{ready?(type==="graduate"?(latest.ratio===null?"未提供":latest.ratio.toFixed(2)):fmt(latest.score)):"—"}{ready&&type==="graduate"&&latest.ratio!==null&&<span> : 1</span>}</div><div className="metric-note">{latest?.year||""} {type==="graduate"?"报名 ÷ 同口径录取":"普通批 · 官方统计"}</div></div><div className="metric"><div className="metric-label">{type==="graduate"?"复试分数线":"录取平均分"}<BookOpen size={17}/></div><div className="metric-value">{ready?fmt(type==="graduate"?latest.score:latest.average):"—"}<span> 分</span></div><div className="metric-note">{type==="graduate"?"官方复试总分要求":"对应省份与科类"}</div></div><div className="metric"><div className="metric-label">{type==="graduate"?"报名人数":"最低录取位次"}<School size={17}/></div><div className="metric-value">{ready?fmt(type==="graduate"?latest.applicants:latest.rank):"—"}<span>{type==="graduate"?" 人":" 名"}</span></div><div className="metric-note">{type==="graduate"?"原表口径见数据来源":`${province} · ${category}类`}</div></div><div className="metric"><div className="metric-label">录取人数<GraduationCap size={17}/></div><div className="metric-value">{ready?fmt(latest.admitted):"—"}<span> 人</span></div><div className="metric-note">实际录取 · 以原表为准</div></div></div>
 <section id="history" className="detail-card"><Tabs value={detail} onValueChange={setDetail}><div className="detail-tabs"><TabsList variant="line"><TabsTrigger value="overview">分数趋势</TabsTrigger><TabsTrigger value="history">历年数据</TabsTrigger><TabsTrigger value="sources">招生资料</TabsTrigger></TabsList><span className="detail-year">{history.length?`${history[0].year}–${history.at(-1)?.year}`:"数据覆盖"}</span></div>
 <TabsContent value="overview"><div className="chart-heading"><div><h3>{type==="graduate"?"历年复试分数线":"历年录取最低分"}</h3><p>{ambiguous?"请选择学院或专业方向，避免混合招生口径。":"只展示已核实的年份，缺失年份不补值。"}</p></div><span className="chart-legend"><i/>{type==="graduate"?"官方复试线":"录取最低分"}</span></div>{chart.length?<ChartContainer config={{score:{label:type==="graduate"?"复试线":"最低分",color:"#3164e7"}}} className="trend-chart"><AreaChart data={chart} margin={{top:20,left:0,right:24,bottom:8}}><defs><linearGradient id="score-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4775f0" stopOpacity={0.22}/><stop offset="100%" stopColor="#4775f0" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} strokeDasharray="4 5" stroke="#e9edf5"/><XAxis dataKey="year" tickLine={false} axisLine={false} tickMargin={12}/><YAxis tickLine={false} axisLine={false} width={44} domain={["dataMin - 20","dataMax + 20"]}/><ChartTooltip content={<ChartTooltipContent/>}/><Area type="linear" dataKey="score" stroke="#3164e7" strokeWidth={3} fill="url(#score-fill)" dot={{r:5,fill:"white",strokeWidth:3}} activeDot={{r:7}} connectNulls={false}/></AreaChart></ChartContainer>:<Empty className="chart-empty"><EmptyHeader><BarChart3 size={34}/><EmptyTitle>{ambiguous?"先选择一个学院或方向":"暂无已核实的分数线"}</EmptyTitle><EmptyDescription>在历年数据中查看已接入统计，或通过招生资料访问官方原文。</EmptyDescription></EmptyHeader></Empty>}<div className="chart-footnote"><Info size={16}/>{type==="graduate"?"复试线是进入复试的要求，不等同于最终录取最低分。":"录取线受省份、科类、批次与选科要求影响，请以当年官方文件为准。"}</div></TabsContent>
 <TabsContent value="history"><div className="table-scroll"><Table><TableHeader><TableRow><TableHead>年份</TableHead><TableHead>专业 / 学院</TableHead><TableHead>{type==="graduate"?"复试线":"最低分"}</TableHead><TableHead>报名</TableHead><TableHead>录取</TableHead><TableHead>报录比</TableHead><TableHead>来源</TableHead></TableRow></TableHeader><TableBody>{[...filtered].sort((a,b)=>b.year-a.year).map((r,i)=><TableRow key={`${r.year}-${r.college}-${i}`} title={r.note}><TableCell className="year-cell">{r.year}</TableCell><TableCell><strong>{r.name}</strong><small>{r.college} · {r.mode}</small></TableCell><TableCell>{r.scoreSource?<a href={r.scoreSource} target="_blank" rel="noreferrer" aria-label={`${r.year}年分数线官方公告`}>{fmt(r.score)} <ExternalLink size={12} className="inline"/></a>:fmt(r.score)}</TableCell><TableCell>{fmt(r.applicants)}</TableCell><TableCell>{fmt(r.admitted)}</TableCell><TableCell>{r.ratio===null?"未提供":`${r.ratio.toFixed(2)} : 1`}</TableCell><TableCell><a href={r.source} target="_blank" rel="noreferrer" aria-label={`${r.year}年官方原表`}><ExternalLink size={16}/></a></TableCell></TableRow>)}</TableBody></Table></div>{!filtered.length&&<Empty><EmptyHeader><EmptyTitle>此条件下尚无已接入数据</EmptyTitle><EmptyDescription>院校可检索不代表其全部专业历史数据已接入。</EmptyDescription></EmptyHeader></Empty>}<div className="table-note">{latest?.note||"缺失数据不会估算或自动补齐。"}</div></TabsContent>
 <TabsContent value="sources"><div className="materials"><h3>从官方原文核对招生信息</h3><p>专业代码、计划人数、学习方式及科目可能逐年调整。</p>{[...new Map(result.rows.map(r=>[r.source,r])).values()].slice(0,8).map(r=><a key={r.source} href={r.source} target="_blank" rel="noreferrer"><BookOpen size={20}/><span><strong>{r.year} 年官方招生统计 / 分数线</strong><small>{r.college} · {r.code}</small></span><ExternalLink size={17}/></a>)}{result.directory?.map(d=><a key={d.url} href={d.url} target="_blank" rel="noreferrer"><Building2 size={20}/><span><strong>{d.name}</strong><small>官方院校信息与招生资料</small></span><ExternalLink size={17}/></a>)}<a href={type==="graduate"?"https://yz.chsi.com.cn/sch/":"https://gaokao.chsi.com.cn/sch/"} target="_blank" rel="noreferrer"><Search size={20}/><span><strong>{type==="graduate"?"研招网全国院校库":"阳光高考全国院校库"}</strong><small>查询尚未接入的院校与专业</small></span><ExternalLink size={17}/></a></div></TabsContent></Tabs></section>
 <div className="coverage-note"><Info size={15}/><span>{latest?.note||"此条件下尚无已接入数据。缺失记录不会自动估算。"}</span></div><div className="trust-strip"><ShieldCheck size={21}/><div><strong>每一个数字，都应有出处。</strong><p>教育部完整高校名录已接入；专业历史统计逐校补充。缺失数据保留为空。</p></div><button onClick={()=>setSourceOpen(true)}>查看覆盖范围</button></div></div>
 <aside className="news-column"><section id="news" className="news-card"><div className="section-title"><div><Newspaper size={19}/><h2>招生情报站</h2></div><button onClick={()=>refreshNews()} aria-label="更新招生资讯"><RefreshCw size={17}/></button></div><p className="section-subtitle">关注变化，让信息先一步到达。</p><Tabs value={newsFilter} onValueChange={setNewsFilter}><TabsList className="news-tabs"><TabsTrigger value="全部">全部</TabsTrigger><TabsTrigger value="简章目录">简章目录</TabsTrigger><TabsTrigger value="复试录取">复试录取</TabsTrigger></TabsList></Tabs><div className="news-list">{articles.filter(a=>newsFilter==="全部"||a.category===newsFilter).slice(0,6).map((a,i)=><a className="news-item" href={a.url} key={a.url+i} target="_blank" rel="noreferrer"><div className="news-meta"><span className={`news-category ${a.category==="简章目录"?"purple":""}`}>{a.category}</span><time>{a.date||"日期见原文"}</time></div><h3>{a.title}</h3><div className="news-source">{a.source}<ExternalLink size={13}/></div></a>)}{!articles.filter(a=>newsFilter==="全部"||a.category===newsFilter).length&&<div className="news-empty"><Newspaper size={28}/><p>{newsStatus}</p><a href={type==="graduate"?"https://yz.chsi.com.cn/kyzx/":"https://gaokao.chsi.com.cn/gkxx/"} target="_blank" rel="noreferrer">查看官方最新资讯 <ExternalLink size={14}/></a></div>}</div><div className="news-update"><Clock3 size={13}/>{newsStatus}</div></section><section className="guide-card"><div className="guide-label">择校小贴士 <BookOpen size={18}/></div><h3>{type==="graduate"?"读懂报录比，再做决定。":"分数之外，也要看位次。"}</h3><p>{type==="graduate"?"同一专业的不同学院、学习方式与专项计划，竞争情况可能不同。比较前，先核对统计口径。":"历年分数波动并不等于难度变化。先选择生源省份与科类，再结合最低录取位次参考。"}</p><button onClick={()=>setSourceOpen(true)}>了解数据口径 <Info size={15}/></button></section></aside></div>
 <footer><div className="footer-brand"><GraduationCap size={18}/>升学指南 ADMISSIONS</div><span>公开招生信息查询 · 以院校及考试主管部门原文为准</span><a href={type==="graduate"?"https://yz.chsi.com.cn/":"https://gaokao.chsi.com.cn/"} target="_blank" rel="noreferrer">{type==="graduate"?"中国研究生招生信息网":"阳光高考"}<ExternalLink size={13}/></a></footer></main>
 <NationalSchools open={nationalOpen} onOpenChange={setNationalOpen} kind={type} onChoose={name=>{setSchool(name);setCode("");setCollege("all");setDetail("sources");query({school:name,code:""});}}/><Sheet open={sourceOpen} onOpenChange={setSourceOpen}><SheetContent className="source-sheet"><SheetHeader><SheetTitle>数据来源与覆盖范围</SheetTitle><SheetDescription>信息从哪里来，以及哪些数据尚未接入。</SheetDescription></SheetHeader><div className="source-sheet-body"><div className="source-badge"><ShieldCheck/>公开官方来源</div><h3>全国高校名录</h3><p>完整导入教育部 2026 年 6 月 18 日发布的普通高校名单：2,952 所，包含本科 1,412 所、高职专科 1,540 所，覆盖内地 31 个省级地区。支持名称搜索、地区筛选与学校标识码查询。名单不含港澳台、成人高校；研究院所等通过研招网查询。名录收录不代表具备研招资格，也不代表专业历史统计齐全。</p><button className="source-national-link" onClick={()=>{setSourceOpen(false);setNationalOpen(true);}}>浏览全国高校库 <Building2 size={15}/></button><h3>历史数据覆盖</h3><ul><li>江苏大学：2024—2026 年分专业报考录取统计及部分复试线，区分全日制与非全日制。</li><li>南京邮电大学：官方网页分专业统计与复试线。</li><li>南开大学：官方历史报考录取统计；部分学院复试线。</li><li>暨南大学：官方报考、录取和推免人数。</li><li>深圳大学：按省份公布的本科分专业录取统计；解析不到的记录显示未接入。</li></ul><h3>公开访问</h3><p>网站已向所有人开放，可直接分享链接使用。</p><h3>如何更新</h3><p>查询时检查已接入官方网页；页面保持打开时每 10 分钟刷新。PDF 资料保留核实后的快照，原文变动或出现新年份时需重新核对。检查时间与数据年份分别显示。全国名录每日最多检查一次官方发布日与总数，发现变化时提示；完整名单更新需重新导入核实。</p><h3>报录比口径</h3><p>报名人数 ÷ 同口径录取人数，仅在两项可比较时计算。含推免、调剂或专项计划的情况见每条记录的说明。比例不能直接当作个人录取概率。</p><h3>尚未接入与未公开</h3><p>均保留为空，不展示模拟数字。高考通常没有公开的学校＋专业报名人数，不生成本科专业报录比。</p><a href="https://yz.chsi.com.cn/" target="_blank" rel="noreferrer">研招网官方入口 <ExternalLink size={15}/></a><a href="https://gaokao.chsi.com.cn/" target="_blank" rel="noreferrer">阳光高考官方入口 <ExternalLink size={15}/></a></div></SheetContent></Sheet></div>;
}
